# Generated by Django 5.2.11 on 2026-04-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_lead_score_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.treatment'),
        ),
    ]
