# Generated by Django 5.2.11 on 2026-04-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_campaign_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='import_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
